---
language: python

jobs:
  include:
    - stage: Lint & Type Check
      python:
        - '3.6'
        - '3.7'
        - '3.8'
      before_install: pip install poetry
      install: poetry install
      script:
        - pre-commit run --all-files
    - stage: Publish
      script: skip
      before_deploy:
        - pip install poetry
        - poetry config pypi-token.pypi $PYPI_TOKEN
        - poetry build
      deploy:
        provider: script
        script: poetry publish
        skip_cleanup: true
        on:
          branch: master
